# Generated by Django 3.2.19 on 2026-02-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=6),
        ),
    ]
