# Generated by Django 3.2.19 on 2026-02-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20260213_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reserved_at',
        ),
    ]
